/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { DailyConnectionEndpoint } from '@pipecat-ai/daily-transport';
import type { APIRequest } from '@pipecat-ai/client-js';

export type TransportType = 'daily' | 'smallwebrtc';

export const TRANSPORT_LABELS: Record<TransportType, string> = {
  daily: 'Daily',
  smallwebrtc: 'SmallWebRTC',
};

const isTransportType = (value: string): value is TransportType =>
  value === 'daily' || value === 'smallwebrtc';

const parseTransports = (value?: string): TransportType[] => {
  const transports = value
    ?.split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(isTransportType);

  return transports?.length ? [...new Set(transports)] : ['daily'];
};

export const AVAILABLE_TRANSPORTS: TransportType[] = parseTransports(
  import.meta.env.VITE_CLAIMPILOT_TRANSPORTS
);

const configuredDefaultTransport = import.meta.env.VITE_CLAIMPILOT_DEFAULT_TRANSPORT;
export const DEFAULT_TRANSPORT: TransportType =
  isTransportType(configuredDefaultTransport) &&
  AVAILABLE_TRANSPORTS.includes(configuredDefaultTransport)
    ? configuredDefaultTransport
    : AVAILABLE_TRANSPORTS[0];

const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || 'http://localhost:7860/start';
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

if (!import.meta.env.VITE_BOT_START_URL) {
  console.warn(
    'VITE_BOT_START_URL not configured, using default: http://localhost:7860/start'
  );
}

const dailyConfig: DailyConnectionEndpoint = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
    transport: "daily",
  },
};

if (botStartPublicApiKey) {
  dailyConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

const smallWebRTCConfig: APIRequest = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: false,
    enableDefaultIceServers: true,
    transport: "webrtc",
  },
};

if (botStartPublicApiKey) {
  smallWebRTCConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

export const TRANSPORT_CONFIG: Record<
  TransportType,
  DailyConnectionEndpoint | APIRequest
> = {
  daily: dailyConfig,
  smallwebrtc: smallWebRTCConfig,
};
